// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpPiUNoEkAFUuBK7IqGN5RpXcvzqigX98',
    appId: '1:780050612250:web:e57a8b455ecdb37f1191a3',
    messagingSenderId: '780050612250',
    projectId: 'flutter-firebase692',
    authDomain: 'flutter-firebase692.firebaseapp.com',
    storageBucket: 'flutter-firebase692.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ks98_sqdxqVe3Eeh0LScBDDcAonBjhc',
    appId: '1:780050612250:android:dd6e7fcde33224251191a3',
    messagingSenderId: '780050612250',
    projectId: 'flutter-firebase692',
    storageBucket: 'flutter-firebase692.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZbk_zILIyGPAEnCNpWm1eN6tDtVw8I3s',
    appId: '1:780050612250:ios:fdaa917685dcc9091191a3',
    messagingSenderId: '780050612250',
    projectId: 'flutter-firebase692',
    storageBucket: 'flutter-firebase692.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZbk_zILIyGPAEnCNpWm1eN6tDtVw8I3s',
    appId: '1:780050612250:ios:fdaa917685dcc9091191a3',
    messagingSenderId: '780050612250',
    projectId: 'flutter-firebase692',
    storageBucket: 'flutter-firebase692.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpPiUNoEkAFUuBK7IqGN5RpXcvzqigX98',
    appId: '1:780050612250:web:952b845c291c1c6c1191a3',
    messagingSenderId: '780050612250',
    projectId: 'flutter-firebase692',
    authDomain: 'flutter-firebase692.firebaseapp.com',
    storageBucket: 'flutter-firebase692.appspot.com',
  );
}
